version: '3.8'

services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    ports:
      - 80:80
    depends_on:
      - database

  database:
      image: postgres:13
      restart: always
      environment:
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_pass
        POSTGRES_DB: test_project
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      ports:
        - 5432:5432

volumes:
  postgres_data:
